### ISSUE TITLE
TK (Techniker Krankenkasse) and possibly other insurers have switched to updated XML schema version 3.0

### ISSUE THREAD

**Issue by uvinw** [alex-therapeutics/diga-api-client#94]
## Problem

Attempting to validate codes results in the error: 
`Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"http://www.gkv-datenaustausch.de/XML-Schema/EDFC0_Pruefung/3.0", local:"Pruefung_Freischaltcode"). Expected elements are <{http://www.gkv-datenaustausch.de/XML-Schema/EDFC0_Pruefung/2.0.0}Pruefung_Freischaltcode>`

**Comment by fongie** [comment]
Hi thanks for opening an issue! I have time to look into this some time next week, as I am currently on vacation. If urgent (which it sounds like), I can review PRs on the subject from here.

Did you see any news on this subject? Feels kind of strange to start using a new version and stop supporting the old one just like that..

On [this official page](https://www.gkv-datenaustausch.de/leistungserbringer/digitale_gesundheitsanwendungen/digitale_gesundheitsanwendungen.jsp) where I got the original files with version 2.0 there is no update, you still get 2.0 if you download from there. Do you by any chance know where to find the version 3 files?

All information will be helpful, if anyone else sees this and can confirm the issue it would help too

**Comment by ManfredfromHH** [comment]
Hi,
we received the information from TK, that it was planned from GKV-SV to switch to 3.0 on 25.08.
but that this information has not reached all involved parties.
We received information about 3.0, too:
The problem from our view is, that for the moment only TK switched to 3.0 already.
Please find informations about 3.0 attached.

[EDFC0-basis_3.0.0.xsd.txt](https://github.com/alex-therapeutics/diga-api-client/files/9431025/EDFC0-basis_3.0.0.xsd.txt)
[EDFC0-Pruefung_3.0.0.xsd.txt](https://github.com/alex-therapeutics/diga-api-client/files/9431027/EDFC0-Pruefung_3.0.0.xsd.txt)
[EDRE0-MVZ_3.0.0.xsd.txt](https://github.com/alex-therapeutics/diga-api-client/files/9431028/EDRE0-MVZ_3.0.0.xsd.txt)
[Krankenkassenverzeichnis_DiGA.xml.txt](https://github.com/alex-therapeutics/diga-api-client/files/9431029/Krankenkassenverzeichnis_DiGA.xml.txt)
[XML-Schema Änderungen Stand 20220524.pdf](https://github.com/alex-therapeutics/diga-api-client/files/9431030/XML-Schema.Anderungen.Stand.20220524.pdf)

**Comment by fongie** [comment]
Thanks a lot for providing the files along with the info @ManfredfromHH ! I will look into a solution next week unless someone else gets there before me, I guess one way to handle it would be to send a v3 request first and then a v2 if it fails, as it seems that we won't really know which insurances upgrade or when. It's not the prettiest solution but then again neither is it for the insurances to do major upgrades without supporting both versions for an interim period.. ;)

**Comment by ManfredfromHH** [comment]
the new version is now officially published on
https://www.gkv-datenaustausch.de/leistungserbringer/digitale_gesundheitsanwendungen/digitale_gesundheitsanwendungen.jsp

**Comment by gtuk** [comment]
I can second that only TK has switched so far to 3.0.
@fongie if you could provide a PR, i would be happy to review/test it asap. Unfortunately i don't have much time to work on it on my own this time

**Comment by fongie** [comment]
Ive got this in mind but have had more urgent things to do at work, just so you know. Ill get to it when I have a chance :)

**Comment by fongie** [comment]
it's a bit of a hack but I understand it's a pressing situation for you guys who are running this in production right now, so sure let's do it! If you PR against the `v3-support` branch I just created here I will merge into that and then release 1.25.0-v2 and 1.25.0-v3 (or similar) versions from the main and v3-support branches respectively. Then, once we create a solution that supports both, we can go back to normal releases.

**Comment by gtuk** [comment]
#98

**Comment by fongie** [comment]
[1.2.5-v3-xml](https://github.com/alex-therapeutics/diga-api-client/releases/tag/1.2.5-v3-xml)
and
[1.2.5-v2-xml](https://github.com/alex-therapeutics/diga-api-client/releases/tag/1.2.5-v2-xml)

are now up on github packages and on their way to maven

the v3 one should support the new xml schemas whereas the v2 one supports the old ones

I will still try to work on a fix for the main branch to support both when I have time, but this can give you a workaround like @gtuk suggested (thanks for providing the v3 PR)

**Comment by gtuk** [comment]
Thanks for the fast merge and release

**Comment by mnin** [comment]
Hey,

https://kkv.gkv-diga.de/ doesn't provide a new file with the specification of 3.0.0.

You can replace the first line in the XML, then it seems to run:

```
<n1:Kostentraeger_Mappingverzeichnis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:n1="http://www.gkv-datenaustausch.de/XML-Schema/EDRE0_MVZ/3.0" xmlns:bas="http://www.gkv-datenaustausch.de/XMLSchema/EDFC0-basis/3.0" version="003.000.000" gueltigab="2022-08-25" xsi:schemaLocation="http://www.gkv-datenaustausch.de/XML-Schema/EDRE0_MVZ/3.0 EDRE0-MVZ_3.0.0.xsd">
```

**Comment by jakob-p** [comment]
Almost all Endpoints switched to v3 today so v2 will be obsolete soon

**Comment by fongie** [comment]
thanks @jakob-p that's good news! then I don't think we should worry about supporting both this time, I havent had time to do that either.. we will just merge the v3 branch into main and release from that on next release

**Comment by gtuk** [comment]
Unfortunately the situation is much more messy/complicated. 
Most of the insurances switched to v3, that is true, but only for the validation requests, not the billing requests (they are still on v2).
That means that for the validation you need to use the insurance mapping file that got released here https://kkv.gkv-diga.de/ (v3), but for the billing request you need to use a mapping file in v2. For this to work you need to update the mapping file manually as described here https://github.com/alex-therapeutics/diga-api-client/wiki/Modifying-the-insurance-company-mapping-file-(Krankenkassenverzeichnis_DiGA.xml)

There is still a problem with insurance endpoints da-api.gkvi.de and kubus-it.da-api.aok.de, based on their validation response they use version v3, but the schema that you should validate is actually v2.
`<Pruefung_Freischaltcode xmlns="http://www.gkv-datenaustausch.de/XML-Schema/EDFC0_Pruefung/2.0.0" nachrichtentyp="FEH" verfahrenskennung="TDFC0" absender="XXXXXX" empfaenger="XXXXXX" version="003.000.000" gueltigab="2022-08-25">`

The problem is  that the diga-api-client is checking the supported version. xsd against version from the xml response and that is not matching. 

The summary/overview for the different endpoints from my side is the following:

Validation:
v3 diga.bitmarck-daten.de
v3 diga-api.tk.de/diga/api/public/rest
da-api.gkvi.de -> see comment above
kubus-it.da-api.aok.de -> see comment above
v3 diga.kkh.de
v3 itscare.da-api.aok.de
v3 arge.da-api.aok.de
diga.apimisc.de -> timeout with a test code request, so no information

**Billing:**
v2 diga.bitmarck-daten.de
v2 diga-api.tk.de/diga/api/public/rest
da-api.gkvi.de -> see comment above
kubus-it.da-api.aok.de -> see comment above
v2 diga.kkh.de
v2 itscare.da-api.aok.de
v2 arge.da-api.aok.de
diga.apimisc.de  -> timeout with a test code request, so no information

**Comment by fongie** [comment]
uhh that does sound like a mess... how are you coping with this right now? is there anything reasonable we can do on the library side to combat this?

**Comment by gtuk** [comment]
After contacting the insurances maintaining the api endpoints da-api.gkvi.de and kubus-it.da-api.aok.de yesterday and told them about the bug on their end they released a hotfix today.
So it seems that now finally all the endpoints are using v3 for the validation. The billing is still using v2 everywhere.
For the moment we still have to maintain both versions of the library, because of version difference between the validation and the billing.
It would probably be good to separate the clients for the validation and the billing as the versions can differ as we see right now and be able to instantiate one client per method (billing, validation

**Comment by gtuk** [comment]
One idea (far from ideal) to tackle these version problems for now is to release the different schema versions under different artifactIs e.g
```
<groupId>com.alextherapeutics</groupId>
<artifactId>diga-api-client-vXXXXX</artifactId>
```
Like this we could at least quickly react to a version change, by creating a new library with a new artifactId and we can import multiple libraries simultaneously and instantiate different clients for different scenarios (validation, billing, even by insurance prefix)

**Comment by jakob-p** [comment]
I just tried the v3 branch and send test bills to all endpoints and its working (exept for bitmarck as they dont accept the test bill as mentioned in the [Readme](https://github.com/alex-therapeutics/diga-api-client#faq) 

So v3 billing seems to be working now?

**Comment by gtuk** [comment]
@jakob-p in the v3-support branch only the xsd files for the validation under https://github.com/alex-therapeutics/diga-api-client/tree/v3-support/src/main/resources/code-xsd are using the v3 version.
The xsd files for the billing under https://github.com/alex-therapeutics/diga-api-client/tree/v3-support/src/main/resources/billing-xsd are still using the old version

**Comment by jakob-p** [comment]
i see, thank you for the clarification and your fix!

**Comment by jakob-p** [comment]
that was just an short issue with the endpoint, not related to V3. They are still running V2 for billing.

**Comment by gtuk** [comment]
@uvinw so far it's still the same as before as far as we can observe, only the validation moved to v3.
As far as i know there are also no immediate plans of bumping the version for billing.

Additionally has every insurance moved to v3 validation it should be much easier now to implemented everything in one library again, instead of having two versions v3 and v2 of the library

**Comment by fongie** [comment]
Does this mean we can merge v3-support branch into main and release from that? Or are there other updates that should be made in regards to this? I was gonna have a hand at supporting both versions but if there's no point anymore I'll avoid it hehe

**Comment by fongie** [comment]
Seems like this can be closed if every api is now using "v3"
